### ISSUE TITLE
Engineer hybrid failure on the nalu-nalu side

### ISSUE THREAD

**Issue by psakievich** [psakievich/exawind-driver#18]

**Comment by pscrozi** [comment]
Wyatt started working on this on 9/26. Tried removing pressure, not removing pressure. Haven't yet reproduced the failure, but still looking.

**Comment by psakievich** [comment]
Able to recreate issue with overset in nalu-nalu side.
Not as dramatic in the nalu-nalu side. 
@mbkuhn was able to recreate in a single mesh.
Parking lot should be used to discuss further.
