### ISSUE TITLE
Programatic: Give clean write up to Mike and Paul

### ISSUE THREAD

**Issue by psakievich** [psakievich/exawind-driver#21]

**Comment by pscrozi** [comment]
Phil taking the lead on this. Michael might need to send some info to Phil on this. 

This is a summary that Mike will be able to send to Ben by end of day on Friday. Plus Phil will write notes for Mike/Paul only as well.

**Comment by pscrozi** [comment]
Mike will send something to Ben later today (9/29). Mike may update what Phil already sent.
