### ISSUE TITLE
Begin assembly of master slide deck for the FY's effort

### ISSUE THREAD

**Issue by psakievich** [psakievich/exawind-driver#22]

**Comment by pscrozi** [comment]
Not worried about this one yet. Let's hold off for now.

**Comment by pscrozi** [comment]
Mike working on this. Wyatt and Michael will support.

It can be fairly sparse. We need a narrative about what was done in both codes. Express approach, novelty, and results. Also, explain the challenges: why this was hard to do. One slide could be a case that we expected to run with and show it blowing up and then showing it run stably with all of the changes. This illustrates the challenge and why there was so much work needed to be done.

**Comment by pscrozi** [comment]
Wyatt putting together a couple of slides today (10/10).

Michael also to work on this today (10/10). 

Mike put a meeting invite on our calendars for Wednesday (10/11) to review the slide deck. Phil might be late to this meeting.

**Comment by pscrozi** [comment]
Mike is currently working on it. It's "there", but needs some clean-up. Michael and Mike will co-PPT this today. Looking for consistency and language. The 2 movies need more description and captions.
