### ISSUE TITLE
Create multiphase branches for the code bases, and integrate into spack-manager

### ISSUE THREAD

**Issue by psakievich** [psakievich/exawind-driver#25]

**Comment by pscrozi** [comment]
Phil planning on working this today (9/29).

**Comment by psakievich** [comment]
Branches created, spack-manager integration is pending: https://github.com/sandialabs/spack-manager/pull/567

Follow on tasks for @wjhorne and @mbkuhn to integrate their changes into these branches.

**Comment by pscrozi** [comment]
Waiting for Jon to review PR. This will allow a consistent build process. We'll have a multi-phase branch. Should be done by the end of today (10/2).

**Comment by pscrozi** [comment]
That's been merged so we can close this.
