### ISSUE TITLE
Debug hybrid failures on nalu-nalu side

### ISSUE THREAD

**Issue by psakievich** [psakievich/exawind-driver#26]

**Comment by psakievich** [comment]
Follow on to #18. Work on a fix

**Comment by pscrozi** [comment]
Wyatt made a fix to the buoyancy term in Nalu-Wind. Removed the issue we were seeing on the Nalu-Wind side. Still need to test in the hybrid case. Reduced the error in velocity by 4 orders of magnitude. The mismatch resolution case was posted by Wyatt. Still working on the reinitialization case.
