### ISSUE TITLE
Figure out how to create a framework for modifying the pressure after reinitialization

### ISSUE THREAD

**Issue by psakievich** [psakievich/exawind-driver#28]

**Comment by pscrozi** [comment]
Wyatt was able to put together a basic method on the Nalu side, and can likely be done on the AMR-Wind side as well. Can change BCs. Worried about the decoupling of pressure: one solver has different pressure than the other. 

Will meet today to discuss (10/2). Wyatt will set this up and invite Michael and Phil and Robert.

**Comment by pscrozi** [comment]
Met on 10/2. Dynamic pressure idea didn't work. Now have a better idea and path forward. Still unclear what to do on the Nalu-Wind side. Have already achieved much better results ignoring the Nalu-Wind pressures. Pressure needs to coincide with own description of the velocity. Michael will push forward with AMR-Wind ignoring pressures from Nalu-Wind. As Wyatt works his side out, this will get even better.

**Comment by pscrozi** [comment]
Wyatt to set up a meeting today (10/5) to discuss best path forward. Will invite Phil and Michael.

Michael is testing using the pressure gradient from Nalu-Wind in AMR-Wind for the simulation.

**Comment by pscrozi** [comment]
Michael was able to run a wave problem and the results look good. 

Michael and Wyatt agree that this is a "Go" now.

Now Michael is going to run the actual milestone problem.

We determined that a lot of the reinit was not needed. Wyatt feels it would be good to have a feature that sets up meshes. We have a good path forward.
